### PR TITLE
Enhancement: Add scheduler_job_name and scheduler_job_description optional inputs

### PR DESCRIPTION
**Pull request by jos-**
# Pull Request Template

## Description

By default, the module generates very long and difficult to read Cloud Scheduler jobs. E.g.
```
description = "Cleanup eu.gcr.io/my-gcp-project-name using grace-0-keep-2-tag_filter-no-tag_filter_any-^([^l]|l($|[^a]|a($|[^t]|t($|[^e]|e($|[^s]|s($|[^t]))))))-tag_filter_any-^([^l]|l($|[^a]|a($|[^t]|t($|[^e]|e($|[^s]|s($|[^t]))))))-dry_run filter"
name        = "grace-0-keep-2-tag_filter-no-tag_filter_any-l-l-a-a-t-t-e-e-s-s-t-tag_filter_any-l-l-a-a-t-t-e-e-s-s-t-dry_run-eu-gcr-io-my-gcp-project-name"
```

This clutters the Cloud Scheduler jobs and can be a reason to not use the module.

This PR provides an option to overwrite the Cloud Scheduler names and descriptions. Non-breaking change. If left empty, the default names and descriptions are used.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

- [x] Tested with these variables set
- [x] Tested without these variables set

## Checklist:

- [x] My PR title follows [semantics prefix](.github/CONTRIBUTING.md#semantic-pull-requests)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings
- [x] I have run pre-commit hooks `pre-commit run -a`
- [x] CI tests are passing

### CODE REVIEW

**Comment by anouarchattouna** [comment]
Hi @jos-, thank you for this PR. Could you please update the PR title (add one of `Feature: `, `Fix: `, `Enhancement: `, etc) and update one of the examples [complete](examples/complete), [minimal](examples/minimal) in order to showcase the usage of these new inputs?

**Comment by jos-** [comment]
@anouarchattouna thanks for the quick reply, updated.

**Comment by anouarchattouna** [comment]
> @anouarchattouna thanks for the quick reply, updated.

Could you also run `pre-commit run -a` ?

**Comment by jos-** [comment]
@anouarchattouna done, thanks.

**Comment by jos-** [comment]
@anouarchattouna can this PR be merged? It's waiting for some time now.

It's a small change, but much increases the acceptance of this project.

**Comment by jos-** [comment]
@fabien-chebel @anouarchattouna @grandria @PascalBourdier can this PR be merged? It's open for more than 2 months now. Thanks 👍

**Review by anouarchattouna — APPROVED** [review]

**Review by lpereir4 — APPROVED** [review]

**Pull request merged**
